version: '3.9'

services:
  app:
    build: .
    restart: always
    container_name: whisper
    env_file:
      - .env
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - shared-data:/shared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


volumes:
  shared-data:
    external: true