apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-config
  namespace: apps-gpu
data:
  TZ: "Asia/Yekaterinburg"
  PYTHONUNBUFFERED: "1"
  LOG_LEVEL: "INFO"
  NVIDIA_VISIBLE_DEVICES: "all"
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  HF_HOME: "/models/huggingface"
  HF_DATASETS_CACHE: "/models/huggingface/datasets"
