apiVersion: v1
kind: Secret
metadata:
  name: whisper-secrets
  namespace: apps-gpu
type: Opaque
stringData:
  HOST: "asterisk-host"
  PORT: "5038"
  USER: "ami-user"
  PASSWORD: "ami-password"

  MYSQL_HOST: "mysql-host"
  MYSQL_DB: "db-name"
  MYSQL_USER: "db-user"
  MYSQL_PASSWORD: "db-password"

  SFTP_HOST: "sftp-host"
  SFTP_USER: "sftp-user"
  SFTP_PASSWORD: "sftp-password"
